<a href="https://colab.research.google.com/github/Soniartha/My_Strategy_Trading_Soniartha/blob/main/LSTMs_Jason_Brownlee_Univariate_Multisteps_with_Vector_Output_Model.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
#Import Library
from numpy import array
from keras.models import Sequential
from keras.layers import LSTM
from keras.layers import Dense

In [3]:
#Define Split Function to Convert sequence data into X and y structure
def split_sequence(sequence, n_steps, n_steps_out):
  X, y = list (), list ()
  for i in range(len(sequence)):
    end_ix = i + n_steps
    out_end_ix = end_ix + n_steps_out
    if out_end_ix > len(sequence):
      break
    seq_x, seq_y = sequence[i : end_ix], sequence[end_ix:out_end_ix]
    X.append(seq_x)
    y.append(seq_y)
  return array(X), array(y)

In [4]:
#Define sequence
series = [1,2,3,4,5,6,7,8,9,10]

In [5]:
#Define n_steps
n_steps, n_steps_out = 3,2

In [6]:
#Split sequence into X and y structure
X, y = split_sequence(series, n_steps, n_steps_out)

In [7]:
#Explore X and y dataset
print(X.shape, y.shape)
for i in range(len(X)):
  print(X[i], y[i])

(6, 3) (6, 2)
[1 2 3] [4 5]
[2 3 4] [5 6]
[3 4 5] [6 7]
[4 5 6] [7 8]
[5 6 7] [8 9]
[6 7 8] [ 9 10]


In [8]:
#Define n_feature
n_feature = 1

In [9]:
#Reshape into 3D data structure
X = X.reshape((X.shape[0], n_steps, n_feature))

In [10]:
#Define LSTMs with Vector Output Model 
model = Sequential()
model.add(LSTM(50, activation= 'relu', input_shape = (n_steps, n_feature)))
model.add(Dense(n_steps_out))
model.compile(optimizer = 'adam', loss = 'mse')

In [11]:
model.summary()

Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
lstm (LSTM)                  (None, 50)                10400     
_________________________________________________________________
dense (Dense)                (None, 2)                 102       
Total params: 10,502
Trainable params: 10,502
Non-trainable params: 0
_________________________________________________________________


In [12]:
model.fit(X, y, epochs= 500, verbose=0)

In [13]:
#Predicted demonstration
x_input = array([8, 9, 10])
x_input = x_input.reshape((1, n_steps, n_feature))
y_hat = model.predict(x_input, verbose= 0)

In [14]:
print(y_hat)

[[10.645218 11.566364]]
